#!/usr/bin/env node
/**
 * Script para inyectar secrets de Encore en el build de la landing page
 * Se ejecuta antes del build de Vite para generar variables de entorno
 */

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Obtener el número de WhatsApp
// Orden de prioridad:
// 1. Variable de entorno WHATSAPP_BUSINESS_NUMBER
// 2. Valor por defecto (para desarrollo)
const whatsappNumber = process.env.WHATSAPP_BUSINESS_NUMBER || '56993112178';

console.log('📱 Inyectando configuración en el build...');
console.log(`   WhatsApp Business Number: ${whatsappNumber}`);

// Generar archivo .env.build.local para Vite
const envContent = `# Auto-generated by inject-secrets.js - DO NOT COMMIT
# Este archivo se genera automáticamente durante el build
VITE_WHATSAPP_NUMBER=${whatsappNumber}
`;

const envPath = join(__dirname, '../.env.build.local');
writeFileSync(envPath, envContent);

console.log('✅ Configuración inyectada correctamente');
console.log(`   Archivo: .env.build.local`);
